fixed bug: there was problem to compile application with minGW under Windows, because of variable name conflict
in C:/Qt/Tools/mingw482_32/i686-w64-mingw32/include/rpc.h line 11 there is used 'interface' name:

#ifndef __OBJC__
#undef interface
#define interface struct
#endif

it caused folowing error:

In file included from C:/Qt/Tools/mingw482_32/i686-w64-mingw32/include/oleidl.h:7:0,
from C:/Qt/Tools/mingw482_32/i686-w64-mingw32/include/ole2.h:38,
from C:/Qt/Tools/mingw482_32/i686-w64-mingw32/include/wtypes.h:12,
from C:/Qt/Tools/mingw482_32/i686-w64-mingw32/include/winscard.h:10,
from C:/Qt/Tools/mingw482_32/i686-w64-mingw32/include/windows.h:97,
from C:\Qt\5.3\mingw482_32\include/QtCore/qt_windows.h:71,
from C:\Qt\5.3\mingw482_32\include/QtGui/qopengl.h:51,
from C:\Qt\5.3\mingw482_32\include\QtGui/qopenglcontext.h:62,
from C:\Qt\5.3\mingw482_32\include\QtGui/QtGui:32,
from ..\src\render_window.hpp:26,
from ..\src\interface.hpp:27,
from ..\src\animation_flight.hpp:27,
from ..\src\animation_flight.cpp:23:
..\src\animation_flight.hpp:72:14: error: expected unqualified-id before 'struct'
cInterface *interface;
            ^
Solution was to use other name of variable.
By the name I have cleaned up naming convention for global variables. Now all start from 'g'